services:
  - type: web
    name: battle-bingo
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: battle-bingo-db
          property: connectionString
databases:
  - name: battle-bingo-db
    plan: starter
